version: '3.8'

volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    env_file: .env
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
