services:
  - type: web
    name: n8n
    region: oregon
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 5
    runtime: docker
