services:
  - type: web
    name: n8n
    region: oregon
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-1bx2.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: ${N8N_ENCRYPTION_KEY}
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 5
    runtime: docker
